name = "dlinoss"
uuid = "909a4949-7478-4630-87d1-78e38341c419"
version = "0.1.0"
authors = ["christos chatzifountas <christos.chatzifountas@biotz.io>"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataLoaders = "2e981812-ef13-4a9c-bfa0-ab13047b12a9"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
HNSW = "540f64fa-c57e-11e8-081c-41422cda4629"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
LowRankApprox = "898213cb-b102-5a47-900c-97e73b919f73"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SentencePiece_jll = "0cc836cc-86cb-5b0e-b290-caf6c31794d8"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"
TextAnalysis = "a2db99b7-8b79-58f8-94bf-bbc811eef33d"
ToeplitzMatrices = "c751599d-da0a-543b-9d20-d0a503d91d24"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
WikiText = "b61fe8a8-5644-50f8-8f27-7d732010995a"
WordTokenizers = "796a5d58-b03d-544a-977e-18100b691f6e"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Adapt = "4.4.0"
Aqua = "0.8.14"
BSON = "0.3.9"
BandedMatrices = "1.9.5"
BenchmarkTools = "1.6.0"
CSV = "0.10.15"
CUDA = "5.9.0"
CairoMakie = "0.15.6"
ChainRulesCore = "1.26.0"
Combinatorics = "1.0.3"
DSP = "0.8.4"
DataLoaders = "0.1.3"
Distances = "0.10.12"
Distributions = "0.25.122"
DrWatson = "2.19.1"
FFTW = "1.10.0"
# Flux = "0.16.5"
Functors = "0.5.2"
HNSW = "0.1.5"
JLD2 = "0.6.2"
JSON3 = "1.14.3"
KernelAbstractions = "0.9.38"
LinearAlgebra = "1.12.0"
LoggingExtras = "1.2.0"
LoopVectorization = "0.12.173"
LowRankApprox = "0.5.5"
Lux = "1.21.1"
LuxCUDA = "0.3.4"
LuxCore = "1.4.2"
MLDatasets = "0.5.15"
NNlib = "0.9.31"
NearestNeighbors = "0.4.22"
Optimisers = "0.4.6"
Parameters = "0.12.3"
Pluto = "0.20.19"
PrettyTables = "3.1.0"
ProgressMeter = "1.11.0"
Random = "1.11.0"
Revise = "3.12.0"
SentencePiece_jll = "0.1.99"
Setfield = "1.1.2"
StaticArrays = "1.9.15"
Statistics = "1.11.1"
StatsBase = "0.33.21"
Tables = "1.12.1"
TensorBoardLogger = "0.1.26"
TextAnalysis = "0.7.5"
ToeplitzMatrices = "0.8.5"
Tullio = "0.3.8"
Unicode = "1.11.0"
UnicodePlots = "3.8.1"
Unitful = "1.25.0"
WikiText = "0.1.0"
WordTokenizers = "0.5.6"
Zygote = "0.7.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
