name = "ossmv2"
uuid = "9eba89b0-d2e8-497a-a11b-9a9ee23f45f2"
version = "0.1.0"
authors = ["christos chatzifountas <christos.chatzifountas@biotz.io>"]

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
HNSW = "540f64fa-c57e-11e8-081c-41422cda4629"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
ParameterSchedulers = "d7d3b36b-41b8-4d0d-a2bf-768c6151755e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
BSON = "0.3"
CUDA = "5.9.3"
Distributions = "0.25.122"
Functors = "0.5.2"
HNSW = "0.1.5"
JSON3 = "1.14.3"
KernelAbstractions = "0.9.39"
LinearAlgebra = "1.12.0"
LoggingExtras = "1.2.0"
LossFunctions = "1.1.1"
Lux = "1.25.0"
LuxCUDA = "0.3.4"
LuxCore = "1.4.2"
NNlib = "0.9.31"
Optimisers = "0.4.6"
ParameterSchedulers = "0.4.3"
Random = "1.11.0"
Revise = "3.12.1"
Statistics = "1.11.0"
StatsBase = "0.34"
